<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <InternalsVisibleTo Include="Mandarin.Services.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.1.0" />
    <PackageReference Include="Bashi.Core" Version="4.0.0" />
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Square" Version="43.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mandarin.Interfaces\Mandarin.Interfaces.csproj" />
  </ItemGroup>

</Project>
