version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - KK578
  assignees:
  - KK578
  ignore:
  - dependency-name: Blazorise
    versions:
    - 0.9.3.3
    - 0.9.3.4
    - 0.9.3.5
  - dependency-name: Blazorise.DataGrid
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.2
    - 0.9.3.3
    - 0.9.3.4
    - 0.9.3.5
  - dependency-name: Blazorise.Icons.FontAwesome
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.2
    - 0.9.3.3
    - 0.9.3.4
    - 0.9.3.5
  - dependency-name: Blazorise.Components
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.2
    - 0.9.3.3
    - 0.9.3.4
    - 0.9.3.5
  - dependency-name: Blazorise.Bootstrap
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.2
    - 0.9.3.3
    - 0.9.3.4
    - 0.9.3.5
  - dependency-name: Google.Protobuf
    versions:
    - 3.15.7
  - dependency-name: AutoFixture
    versions:
    - 4.16.0
  - dependency-name: Grpc.Tools
    versions:
    - 2.35.0
    - 2.36.0
    - 2.36.1
    - 2.36.4
  - dependency-name: Grpc.AspNetCore.Web
    versions:
    - 2.35.0
    - 2.36.0
  - dependency-name: Microsoft.AspNetCore.Mvc.Testing
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Components.WebAssembly.Authentication
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Moq
    versions:
    - 4.16.0
    - 4.16.1
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
    - 3.0.3
  - dependency-name: Microsoft.AspNetCore.Authentication.OpenIdConnect
    versions:
    - 5.0.2
- package-ecosystem: npm
  directory: "/src/Mandarin"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - KK578
  assignees:
  - KK578
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: tailwindcss
    versions:
    - 2.0.3
    - 2.0.4
    - 2.1.1
  - dependency-name: simple-git
    versions:
    - 2.32.0
    - 2.34.2
    - 2.35.0
    - 2.35.1
    - 2.35.2
    - 2.36.0
    - 2.36.1
    - 2.36.2
    - 2.37.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
