<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)/../Mandarin.Tests.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup>
    <VSTestLogger>trx%3BLogFileName=$(MSBuildProjectName).trx</VSTestLogger>
    <VSTestResultsDirectory>$(MSBuildThisFileDirectory)/reports/</VSTestResultsDirectory>
    <CollectCoverage>true</CollectCoverage>
    <MergeWith>$(MSBuildThisFileDirectory)../coverage/coverage.json</MergeWith>
    <CoverletOutput>$(MSBuildThisFileDirectory)../coverage/$(MSBuildProjectName).opencover.xml</CoverletOutput>
    <CoverletOutputFormat>opencover</CoverletOutputFormat>
    <Exclude>[Mandarin.Views]*,[Microsoft.*]*,[*.Tests]*</Exclude>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="8.0.1" />
    <PackageReference Include="FluentAssertions" Version="7.2.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="XUnit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="XunitXml.TestLogger" Version="8.0.0" />
  </ItemGroup>

</Project>
