// <auto-generated />

using System.CodeDom.Compiler;
using Microsoft.EntityFrameworkCore.Migrations;
#pragma warning disable 1413
#pragma warning disable 1591
#pragma warning disable 1600
#pragma warning disable 1601

namespace Mandarin.Database.Migrations
{
    [GeneratedCode("dotnet-ef", "3.1.5")]
    public partial class InitialCreatePatch : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "rate",
                schema: "billing",
                table: "commission_rate_group",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "rate",
                schema: "billing",
                table: "commission_rate_group",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int));
        }
    }
}
