// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Mandarin.Database.Migrations
{
    [ExcludeFromCodeCoverage]
    [DbContext(typeof(MandarinDbContext))]
    internal partial class MandarinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Mandarin.Models.Artists.Stockist", b =>
                {
                    b.Property<int>("StockistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("stockist_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("StatusCode")
                        .HasColumnName("stockist_status")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<string>("StockistCode")
                        .IsRequired()
                        .HasColumnName("stockist_code")
                        .HasColumnType("character varying(6)")
                        .HasMaxLength(6);

                    b.Property<string>("StockistName")
                        .IsRequired()
                        .HasColumnName("stockist_name")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.HasKey("StockistId");

                    b.HasIndex("StatusCode");

                    b.HasIndex("StockistCode")
                        .IsUnique()
                        .HasName("stockist_stockist_code_key");

                    b.ToTable("stockist","inventory");
                });

            modelBuilder.Entity("Mandarin.Models.Artists.StockistDetail", b =>
                {
                    b.Property<int>("StockistId")
                        .HasColumnName("stockist_id")
                        .HasColumnType("integer");

                    b.Property<string>("EmailAddress")
                        .HasColumnName("email_address")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FacebookHandle")
                        .HasColumnName("facebook_handle")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<string>("ImageUrl")
                        .HasColumnName("image_url")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<string>("InstagramHandle")
                        .HasColumnName("instagram_handle")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<string>("TumblrHandle")
                        .HasColumnName("tumblr_handle")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<string>("TwitterHandle")
                        .HasColumnName("twitter_handle")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<string>("WebsiteUrl")
                        .HasColumnName("website_url")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.HasKey("StockistId")
                        .HasName("stockist_detail_pkey");

                    b.ToTable("stockist_detail","inventory");
                });

            modelBuilder.Entity("Mandarin.Models.Commissions.Commission", b =>
                {
                    b.Property<int>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("commission_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("end_date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("inserted_at")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("RateGroupId")
                        .HasColumnName("rate_group")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("start_date")
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int?>("StockistId")
                        .HasColumnName("stockist_id")
                        .HasColumnType("integer");

                    b.HasKey("CommissionId");

                    b.HasIndex("RateGroupId");

                    b.HasIndex("StockistId");

                    b.ToTable("commission","billing");
                });

            modelBuilder.Entity("Mandarin.Models.Commissions.CommissionRateGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("group_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Rate")
                        .HasColumnName("rate")
                        .HasColumnType("integer");

                    b.HasKey("GroupId")
                        .HasName("commission_rate_group_pkey");

                    b.ToTable("commission_rate_group","billing");
                });

            modelBuilder.Entity("Mandarin.Models.Common.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("status_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnName("status_code")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.HasKey("StatusId");

                    b.HasIndex("StatusCode")
                        .IsUnique()
                        .HasName("status_status_code_key");

                    b.ToTable("status","static");
                });

            modelBuilder.Entity("Mandarin.Models.Artists.Stockist", b =>
                {
                    b.HasOne("Mandarin.Models.Common.Status", "Status")
                        .WithMany("Stockists")
                        .HasForeignKey("StatusCode")
                        .HasConstraintName("stockist_stockist_status_fkey")
                        .HasPrincipalKey("StatusCode");
                });

            modelBuilder.Entity("Mandarin.Models.Artists.StockistDetail", b =>
                {
                    b.HasOne("Mandarin.Models.Artists.Stockist", "Stockist")
                        .WithOne("Details")
                        .HasForeignKey("Mandarin.Models.Artists.StockistDetail", "StockistId")
                        .HasConstraintName("stockist_detail_stockist_id_fkey")
                        .IsRequired();
                });

            modelBuilder.Entity("Mandarin.Models.Commissions.Commission", b =>
                {
                    b.HasOne("Mandarin.Models.Commissions.CommissionRateGroup", "RateGroup")
                        .WithMany("Commissions")
                        .HasForeignKey("RateGroupId")
                        .HasConstraintName("commission_rate_group_fkey");

                    b.HasOne("Mandarin.Models.Artists.Stockist", "Stockist")
                        .WithMany("Commissions")
                        .HasForeignKey("StockistId")
                        .HasConstraintName("commission_stockist_id_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
