<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <UserSecretsId>3f0fc735-6e13-4ab9-85e8-0bf30131674a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="__admin/mappings/*.json" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Migrations/*.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.1.0" />
    <PackageReference Include="Bashi.Tests.Framework" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.5" />
    <PackageReference Include="Serilog.Sinks.XUnit" Version="3.0.19" />
    <PackageReference Include="WireMock.Net" Version="2.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mandarin\Mandarin.csproj" />
    <ProjectReference Include="..\Mandarin.Tests.Data\Mandarin.Tests.Data.csproj" />
  </ItemGroup>

</Project>
