<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations/*.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.1.0" />
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Bashi.Core" Version="4.0.0" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="dbup-core" Version="6.1.1" />
    <PackageReference Include="dbup-postgresql" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="Npgsql.NodaTime" Version="10.0.2" />
    <PackageReference Include="Serilog" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mandarin.Interfaces\Mandarin.Interfaces.csproj" />
  </ItemGroup>

</Project>
